import inspect from "vite-plugin-inspect";
import { resolve } from "path";

export default {
  plugins: [inspect()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        notif: resolve(__dirname, "notification.html"),
        userList: resolve(__dirname, "users/index.html"),
        userCreate: resolve(__dirname, "users/create.html"),
        userProfile: resolve(__dirname, "users/profile.html"),
        walletsList: resolve(__dirname, "wallets/index.html"),
        walletsCreate: resolve(__dirname, "wallets/create.html"),
        walletsProfile: resolve(__dirname, "wallets/profile.html"),
        supplierList: resolve(__dirname, "supplier/index.html"),
        supplierCreate: resolve(__dirname, "supplier/create.html"),
        supplierProfile: resolve(__dirname, "supplier/profile.html"),
        sitesList: resolve(__dirname, "sites/index.html"),
        sitesCreate: resolve(__dirname, "sites/create.html"),
        sitesProfile: resolve(__dirname, "sites/profile.html"),
        transactions: resolve(__dirname, "transactions/index.html"),
        support: resolve(__dirname, "support/index.html"),
        receiptList: resolve(__dirname, "receipt/index.html"),
        receiptCheque: resolve(__dirname, "receipt/cheque.html"),
        reAccountList: resolve(__dirname, "re-account/index.html"),
        reAccountCreate: resolve(__dirname, "re-account/create.html"),
        reAccountEdit: resolve(__dirname, "re-account/edit.html"),
        reAccountProfile: resolve(__dirname, "re-account/profile.html"),
        reAccountSale: resolve(__dirname, "re-account/sale.html"),
        paymentProfile: resolve(__dirname, "payment/profile.html"),
        paymentCreate: resolve(__dirname, "payment/create.html"),
        marketersList: resolve(__dirname, "marketers/index.html"),
        marketersCreate: resolve(__dirname, "marketers/create.html"),
        marketersProfile: resolve(__dirname, "marketers/profile.html"),
        flyTicket: resolve(__dirname, "fly/ticket.html"),
        flyCreate: resolve(__dirname, "fly/create.html"),
        flyHand: resolve(__dirname, "fly/hand.html"),
        companyList: resolve(__dirname, "company/index.html"),
        companyCreate: resolve(__dirname, "company/create.html"),
        companyProfile: resolve(__dirname, "company/profile.html"),
        coding: resolve(__dirname, "coding/index.html"),
        chPaidList: resolve(__dirname, "ch-paid/index.html"),
        chPaidCheque: resolve(__dirname, "ch-paid/cheque.html"),
        bankList: resolve(__dirname, "bank/index.html"),
        bankCheque: resolve(__dirname, "bank/cheque.html"),
        announcementsList: resolve(__dirname, "Announcements/index.html"),
        announcementsCheque: resolve(__dirname, "Announcements/cheque.html"),
        accountingList: resolve(__dirname, "accounting/index.html"),
        accountingCreate: resolve(__dirname, "accounting/create.html"),
        accountingEdit: resolve(__dirname, "accounting/edit.html"),
        accountingProfile: resolve(__dirname, "accounting/profile.html"),
        accountingSale: resolve(__dirname, "accounting/sale.html"),
      },
    },
  },
};
